Repository packit/packit-service, pull requests merged in 2019-11, with the labels that each got.

#197 Properly handle failed CoprBuildStartHandler
  packit_service/worker/fedmsg_handlers.py
Labels: mergeit, ready-for-review

#198 Add config for stale bot
  .github/stale.yml
Labels: mergeit

#200 one-liner .. oh .. and this .. and also this ... rewrite all job handlers
  packit_service/worker/comment_action_handler.py
  packit_service/worker/handler.py
  packit_service/worker/jobs.py
Labels: mergeit

#199 First shot on integration tests for copr build
  CONTRIBUTING.md
  Makefile
  files/check-inside-openshift.yaml
  files/recipe-tests.yaml
  files/run_tests.sh
  files/test-in-openshift-get-data.yaml
  files/test-in-openshift-secrets.yaml
  files/test-in-openshift.yaml
  files/zuul-tests.yaml
  tests/data/webhooks/copr_build/pr_comment.json
  tests/data/webhooks/copr_build/pr_comment_not_collaborator.json
  tests/data/webhooks/copr_build/pr_synchronize.json
  tests/integration/test_copr.py
  tests/openshift_integration/__init__.py
  tests_requre/README.md
  tests_requre/__init__.py
  tests_requre/openshift_integration/__init__.py
  tests_requre/openshift_integration/base.py
  tests_requre/openshift_integration/test_copr.py
  tests_requre/openshift_integration/test_fedpkg.py
  tests_requre/test_data/README.md
  tests_requre/test_data/test_copr/tests_requre.openshift_integration.test_copr.Copr.test_not_collaborator.yaml
  tests_requre/test_data/test_copr/tests_requre.openshift_integration.test_copr.Copr.test_submit_copr_build_pr_comment.yaml
  tests_requre/test_data/test_copr/tests_requre.openshift_integration.test_copr.Copr.test_submit_copr_build_pr_event.yaml
  tests_requre/test_data/test_fedpkg/tests_requre.openshift_integration.test_fedpkg.FedPkg.test_fedpkg_clone.yaml
Labels: ready-for-review

#203 fromisoformat() doesn't handle Zulu time ("Z")
  packit_service/service/events.py
  tests/data/webhooks/installation_created.json
  tests/unit/test_events.py
Labels: mergeit

#208 [CoprBuildHandler.run_copr_build()] report no targets
  packit_service/worker/copr_build.py
Labels: mergeit

#215 Add pkgs.fedoraproject.org to known_hosts
  files/recipe-worker.yaml
  files/run_worker.sh
Labels: mergeit

#207 mach ordnung in Makefile
  CONTRIBUTING.md
  Makefile
  files/packit-service-image.yaml
Labels: mergeit

#219 Ignore X-GitHub-Events we don't care about
  packit_service/service/api/webhooks.py
  packit_service/worker/whitelist.py
Labels: mergeit

#227 [fedmsg] install copr json schemas
  files/install-deps.yaml
Labels: mergeit

#229 [Fedmsg.Consumerino.fedora_messaging_callback()] log timestamp and message body
  packit_service/cli/listen_to_fedora_messaging.py
  packit_service/fedmsg/consumer.py
Labels: mergeit

#238 even better notification message
  packit_service/worker/github_handlers.py
Labels: mergeit
