Repository packit/packit-service, pull requests merged in 2020-09, with the labels that each got.

#791 Make the koji builds endpoint more consistent with the copr endpoint
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/service/api/koji_builds.py
  tests_requre/service/test_api.py
Labels: mergeit, ready-for-review

#740 Reporting build status while no permission
  files/docker/Dockerfile.tests
  packit_service/service/api/webhooks.py
  packit_service/service/events.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/reporting.py
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_reporting.py
Labels: mergeit

#795 Store submission time of SRPM Builds
  alembic/versions/a0e48c400be4_store_submit_time_of_srpm_builds.py
  packit_service/models.py
  packit_service/service/api/srpm_builds.py
  tests_requre/service/test_api.py
Labels: mergeit

#796 [Zuul] use oc-cluster-up base job
  .zuul.yaml
  files/deployment.yaml
  files/install-openshift.yaml
  files/setup-openshift.yaml
Labels: mergeit

#799 Add 'push_dev_images: true' to files/deployment.yaml
  files/deployment.yaml
Labels: mergeit

#798 Better Testing-farm response for cluster problems
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/testing_farm.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#801 Turn PR labels into a set in the handler
  packit_service/worker/handlers/pagure_handlers.py
Labels: mergeit

#804 [deployment.yaml] Set 'with_pushgateway: false' in dev.yml
  files/deployment.yaml
Labels: mergeit

#800 Support AWS SQS & RDS
  .pre-commit-config.yaml
  Makefile
  docker-compose.yml
  files/install-deps-worker.yaml
  files/install-deps.yaml
  files/test-in-openshift.yaml
  packit_service/celerizer.py
  packit_service/service/templates/layout.html
  packit_service/service/templates/srpm_logs.html
  packit_service/worker/tasks.py
  setup.cfg
Labels: mergeit

#805 [models.get_pg_url] POSTGRES_SERVICE_HOST -> POSTGRESQL_HOST
  packit_service/models.py
Labels: mergeit

#806 Fix gitlab namespaces in webhook
  packit_service/service/api/webhooks.py
  tests/unit/test_webhooks.py
Labels: gitlab, mergeit

#808 Set pr_id in StatusReporter called from TestingFarmResultsHandler
  packit_service/worker/handlers/testing_farm_handlers.py
Labels: mergeit

#809 Require build for Pagure copr build comment when tests defined
  packit_service/worker/handlers/pagure_handlers.py
  tests/unit/test_jobs.py
Labels: mergeit

#810 files/install-deps[-worker].yaml - install pycurl as rpm
  files/install-deps-worker.yaml
  files/install-deps.yaml
Labels: mergeit

#812 Parse multi part namespaces in event parsing
  packit_service/service/events.py
  packit_service/worker/parser.py
  tests/data/webhooks/gitlab/issue_comment.json
  tests/data/webhooks/gitlab/mr_comment.json
  tests/data/webhooks/gitlab/mr_event.json
  tests/data/webhooks/gitlab/mr_update_event.json
  tests/data/webhooks/gitlab/push_branch.json
  tests/data/webhooks/gitlab/push_with_one_commit.json
  tests/unit/test_events.py
  tests/unit/test_whitelist.py
Labels: mergeit

#814 Better gitlab token issue text
  packit_service/service/api/webhooks.py
Labels: mergeit, user-experience

#815 Congratulations comment for GitLab
  packit_service/worker/handlers/fedmsg_handlers.py
Labels: mergeit, user-experience

#813 Add koji builds to /projects/.../prs & /projects/.../branches API endpoints
  packit_service/models.py
  packit_service/service/api/projects.py
  packit_service/service/api/testing_farm.py
  tests_requre/database/test_models.py
  tests_requre/service/test_api.py
Labels: mergeit

#816 Add header to status table
  packit_service/worker/reporting.py
  tests/unit/test_reporting.py
Labels: gitlab, mergeit, user-experience

#819 Improve the copr project naming
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: copr, gitlab, mergeit, 🌞 Friday 🤟

#821 pre-commit and black badge
  README.md
Labels: mergeit, 🌞 Friday 🤟

#823 [files/install-deps*.yaml] install pycurl build dependencies
  files/install-deps-worker.yaml
  files/install-deps.yaml
  setup.cfg
Labels: mergeit

#820 Add pyupgrade to pre-commit
  .pre-commit-config.yaml
  packit_service/worker/whitelist.py
  tests/integration/test_listen_to_fedmsg.py
Labels: mergeit, 🌞 Friday 🤟

#824 Pin celery to 4.4.7
  files/install-deps-worker.yaml
  files/install-deps.yaml
Labels: mergeit

#827 Push metrics about created copr-builds
  packit_service/worker/build/copr_build.py
  packit_service/worker/monitoring.py
  tests/unit/test_copr_build.py
Labels: mergeit

#828 Don't raise exception when REDIS_SERVICE_HOST not set
  Makefile
  packit_service/celerizer.py
Labels: mergeit

#831 Support for enabled_private_namespaces
  packit_service/config.py
  packit_service/schema.py
  packit_service/worker/jobs.py
  tests/unit/test_config.py
  tests/unit/test_steve.py
Labels: mergeit

#834 Update contribution guidelines
  CONTRIBUTING.md
Labels: mergeit

#835 Response for non-existing target
  files/scripts/webhook.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/testing_farm.py
  tests/unit/test_copr_build.py
Labels: mergeit
