Repository packit/packit-service, pull requests merged in 2020-10, with the labels that each got.

#826 Base images on F32
  files/docker/Dockerfile.tests
  files/install-deps-worker.yaml
  files/install-deps.yaml
  files/run_httpd.sh
  files/run_tests.sh
Labels: mergeit

#837 no hardcoded mapping
  packit_service/trigger_mapping.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/jobs.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
  tests/unit/test_jobs.py
  tests/unit/test_koji_build.py
  tests_requre/openshift_integration/test_fedpkg.py
Labels: mergeit, ready-for-review

#722 Remove GithubWebhook.interested()
  packit_service/service/api/webhooks.py
Labels: mergeit

#840 Remove files/setup-openshift.yaml & files/tasks/zuul-project-setup.yaml
  .zuul.yaml
  Makefile
  files/deployment.yaml
  files/packit-service-image.yaml
  files/setup-openshift.yaml
  files/tasks/zuul-project-setup.yaml
  files/zuul-tests-requre.yaml
  files/zuul-tests.yaml
Labels: hacktoberfest-accepted, mergeit

#843 already enable requre test for fedpkg
  CONTRIBUTING.md
  tests_requre/openshift_integration/base.py
  tests_requre/openshift_integration/test_data/test_copr/tests_requre.openshift_integration.test_copr.Copr.test_not_collaborator.yaml
  tests_requre/openshift_integration/test_data/test_copr/tests_requre.openshift_integration.test_copr.Copr.test_submit_copr_build_pr_comment.yaml
  tests_requre/openshift_integration/test_data/test_fedpkg/tests_requre.openshift_integration.test_fedpkg.FedPkg.test_fedpkg_clone.yaml
  tests_requre/openshift_integration/test_data/test_fedpkg/tests_requre.openshift_integration.test_fedpkg.FedPkg.test_fedpkg_clone.yaml.tmpxholg1bu_1.tar.xz
  tests_requre/openshift_integration/test_fedpkg.py
Labels: mergeit

#844 Remove test dependency on packit constant
  tests/unit/test_build_helper.py
Labels: mergeit, ready-for-review

#845 [packit-service-tests-requre] reuse 'make generate-local-secrets' from deployment repo
  .zuul.yaml
  files/deployment.yaml
Labels: mergeit

#850 Pin sentry-sdk to 0.18.0
  files/install-deps-worker.yaml
  files/install-deps.yaml
Labels: mergeit

#852 Set error status when running non-scratch production build
  packit_service/constants.py
  packit_service/worker/build/koji_build.py
  tests/unit/test_koji_build.py
Labels: mergeit

#853 Update pre-commit configuration for prettier
  .pre-commit-config.yaml
Labels: mergeit

#849 Test the git config values in worker /src
  files/check-inside-openshift.yaml
Labels: mergeit

#856 Update unit tests
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
Labels: mergeit, ready-for-review
