Repository packit/packit-service, pull requests merged in 2020-03, with the labels that each got.

#447 do not comment on PRs, instead store output as logs
  packit_service/models.py
  packit_service/service/events.py
  packit_service/service/urls.py
  packit_service/service/views.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/utils.py
  tests/integration/test_issue_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_copr_build.py
  tests/unit/test_steve.py
  tests/unit/test_views.py
Labels: mergeit, ready-for-review

#433 Control packit-service with the command embedded in a comment.
  packit_service/worker/jobs.py
  tests/data/webhooks/github_pr_comment_embedded_command.json
  tests/integration/test_pr_comment.py
Labels: mergeit

#449 use proper github failure status
  packit_service/constants.py
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: mergeit

#448 Pre-check for jobs and release/push copr triggers
  packit_service/service/events.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/__init__.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
  packit_service/worker/testing_farm.py
  tests/conftest.py
  tests/data/webhooks/github_push.json
  tests/unit/test_build_helper.py
  tests/unit/test_events.py
Labels: mergeit

#450 Use enum for status states and fix setting of status
  packit_service/constants.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/reporting.py
  packit_service/worker/testing_farm.py
  packit_service/worker/whitelist.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_copr_build.py
  tests/unit/test_testing_farm.py
  tests/unit/test_whitelist.py
Labels: mergeit

#451 Revert getting job per trigger
  packit_service/constants.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/handlers/github_handlers.py
Labels: mergeit

#452 Fix ref for pr events and validate push events
  packit_service/service/events.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/parser.py
  packit_service/worker/testing_farm.py
  packit_service/worker/whitelist.py
  tests/data/webhooks/github_push_branch.json
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#443 Store the date/time of triggering new copr build
  alembic/env.py
  alembic/versions/70dcb6140e11_store_build_datetime.py
  packit_service/models.py
  packit_service/service/models.py
  tests_requre/test_db.py
Labels: mergeit

#455 enable configuring "Congratulations!" PR comment
  packit_service/worker/handlers/fedmsg_handlers.py
  tests/integration/test_listen_to_fedmsg.py
Labels: mergeit

#456 SA: rollback transaction on exc
  packit_service/models.py
  tests_requre/test_db.py
Labels: mergeit

#458 Sentry integration for service
  files/install-deps-worker.yaml
  files/install-deps.yaml
  packit_service/celerizer.py
  packit_service/sentry_integration.py
  packit_service/service/app.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/testing_farm.py
  tests/integration/test_release_event.py
  tests/unit/test_copr_build.py
Labels: mergeit

#453 Split job and jobconfig (service)
  packit_service/config.py
  packit_service/service/events.py
  packit_service/trigger_mapping.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/whitelist.py
  tests/integration/test_handler.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_testing_farm.py
  tests/unit/test_whitelist.py
Labels: mergeit

#460 Install sentry in the worker image
  files/install-deps-worker.yaml
Labels: mergeit

#471 Fix job type attribute
  packit_service/trigger_mapping.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/handlers/github_handlers.py
  tests/conftest.py
  tests/integration/test_handler.py
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
Labels: mergeit

#474 Fix valueerror when no-action-needed PR comment is followed by a space.
  packit_service/worker/jobs.py
  tests/integration/test_pr_comment.py
Labels: mergeit

#472 [GitHubIssueCommentProposeUpdateHandler] include new PR url
  packit_service/worker/handlers/github_handlers.py
  tests/integration/test_issue_comment.py
Labels: mergeit

#467 images: store git HEAD info in the image
  Dockerfile
  Dockerfile.worker
  Dockerfile.worker.prod
Labels: mergeit

#475 more tests to exercise /packit comment parsing
  tests/integration/test_pr_comment.py
Labels: mergeit

#473 Easier local development of p-s
  CONTRIBUTING.md
  Dockerfile
  docker-compose.yml
  files/packit-httpd.conf
  files/tasks/httpd.yaml
  packit_service/service/app.py
Labels: mergeit

#468 Use project_dir variable in playbooks
  files/packit-service-image.yaml
  files/tasks/zuul-project-setup.yaml
  files/zuul-tests-requre.yaml
  files/zuul-tests.yaml
Labels: mergeit

#476 Rework mapping
  packit_service/service/events.py
  packit_service/trigger_mapping.py
  packit_service/worker/handlers/__init__.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/comment_action_handler.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/jobs.py
  tests/unit/test_jobs.py
Labels: mergeit, ready-for-review

#483 fix p-s deployment in zuul
  files/deployment.yaml
  files/packit-service-image.yaml
Labels: mergeit

#480 Add koji build handlers and simplify the handler decorators
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  tests/unit/test_jobs.py
Labels: mergeit

#485 Send commit sha as a git-ref to testing farm
  packit_service/worker/testing_farm.py
Labels: mergeit

#486 Test for testing farm
  tests/integration/test_listen_to_fedmsg.py
Labels: mergeit

#487 Permission problem is not sentry issue
  packit_service/worker/handlers/github_handlers.py
Labels: mergeit

#479 Rewrite the copr-builds part of the API using PostgresSQL instead of Redis
  alembic/versions/61d0f32eda4b_added_project_name_and_git_fields.py
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/worker/build/copr_build.py
  tests_requre/test_db.py
Labels: mergeit

#496 Not overwrite git_ref in CoprBuildEvent
  packit_service/service/events.py
  tests/unit/test_events.py
Labels: mergeit

#493 Fix error in API when old data exists.
  packit_service/service/api/copr_builds.py
  tests/unit/test_api.py
Labels: mergeit

#497 deployment: process path_to_secrets actually + random commits
  Makefile
  files/check-inside-openshift.yaml
  files/deployment.yaml
Labels: mergeit, ready-for-review

#499 Fix copr project name for testing farm and add response url
  packit_service/worker/build/build_helper.py
  packit_service/worker/testing_farm.py
  tests/integration/test_listen_to_fedmsg.py
Labels: mergeit, testing-farm

#498 Allow pre-releases in propose-update triggered by comment
  packit_service/service/events.py
  packit_service/worker/handlers/github_handlers.py
  tests/conftest.py
Labels: mergeit

#505 Fix testing farm result mapping
  packit_service/trigger_mapping.py
  tests/unit/test_jobs.py
Labels: mergeit

#511 CI: create certs for centos things
  files/deployment.yaml
Labels: mergeit

#510 Fix event argument for handlers
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/jobs.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#490 periodically check the status of a copr build
  packit_service/celerizer.py
  packit_service/constants.py
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/tasks.py
  tests/unit/test_copr_build.py
  tests_requre/openshift_integration/__init__.py
  tests_requre/openshift_integration/test_copr.py
  tests_requre/test_data/test_copr/tests_requre.openshift_integration.test_copr.Copr.test_not_collaborator.yaml
  tests_requre/test_data/test_copr/tests_requre.openshift_integration.test_copr.Copr.test_submit_copr_build_pr_comment.yaml
  tests_requre/test_data/test_fedpkg/tests_requre.openshift_integration.test_fedpkg.FedPkg.test_fedpkg_clone.yaml
  tests_requre/test_db.py
  tests_requre/test_tasks.py
Labels: mergeit, ready-for-review

#513 Right testing farm response url
  packit_service/worker/build/build_helper.py
  packit_service/worker/testing_farm.py
  tests/integration/test_listen_to_fedmsg.py
Labels: mergeit

#501 Move Whitelist from Redis to Postgres
  alembic/versions/4292b00185bf_whitelist.py
  packit_service/constants.py
  packit_service/models.py
  packit_service/service/events.py
  packit_service/worker/whitelist.py
  tests/unit/test_whitelist.py
  tests_requre/test_db.py
Labels: mergeit

#519 Fix tests after merging packit-service/packit#768
  .pre-commit-config.yaml
  tests/integration/test_issue_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_steve.py
Labels: mergeit

#521 Minor API Bugfixes
  packit_service/models.py
  packit_service/service/api/copr_builds.py
Labels: mergeit

#522 Use Flask-RESTX instead of abandoned Flask-RESTPLUS
  files/install-deps-worker.yaml
  files/install-deps.yaml
  packit_service/service/api/__init__.py
  packit_service/service/api/copr_builds.py
  packit_service/service/api/healthz.py
  packit_service/service/api/installations.py
  packit_service/service/api/parsers.py
  packit_service/service/api/tasks.py
  packit_service/service/api/testing_farm.py
  packit_service/service/api/webhooks.py
  packit_service/service/api/whitelist.py
Labels: mergeit

#520 Save task results in psql instead of redis
  alembic/versions/dc1beda6749e_add_tables_for_task_results.py
  packit_service/celerizer.py
  packit_service/models.py
  packit_service/service/api/tasks.py
  packit_service/worker/tasks.py
  tests_requre/test_db.py
Labels: mergeit

#502 Add triggers to dtb
  alembic/versions/d90948124e46_add_tables_for_triggers_koji_and_tests.py
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/service/db_triggers.py
  packit_service/service/events.py
  packit_service/service/views.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
  packit_service/worker/tasks.py
  packit_service/worker/testing_farm.py
  packit_service/worker/whitelist.py
  tests/conftest.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_jobs.py
  tests/unit/test_steve.py
  tests/unit/test_testing_farm.py
  tests/unit/test_views.py
  tests/unit/test_whitelist.py
  tests_requre/database/__init__.py
  tests_requre/database/conftest.py
  tests_requre/database/test_models.py
  tests_requre/database/test_tasks.py
  tests_requre/database/test_whitelist.py
  tests_requre/test_db.py
Labels: database, mergeit

#525 Add flexmock to the service
  files/install-deps.yaml
Labels: mergeit

#527 Fix triggers creation in database
  packit_service/models.py
  packit_service/worker/build/copr_build.py
  tests_requre/database/conftest.py
  tests_requre/database/test_models.py
  tests_requre/database/test_tasks.py
Labels: mergeit
