Repository packit/packit-service, pull requests merged in 2020-04, with the labels that each got.

#529 Two db fixes
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/worker/testing_farm.py
  tests/integration/test_listen_to_fedmsg.py
  tests_requre/database/conftest.py
  tests_requre/database/test_models.py
Labels: mergeit

#530 Support different triggers in copr build view
  packit_service/service/views.py
  tests/unit/test_views.py
  tests_requre/database/conftest.py
  tests_requre/database/test_models.py
Labels: mergeit

#528 Add a psql model for Github installations
  alembic/versions/d7c2f99cd14d_add_a_table_for_github_installations.py
  packit_service/models.py
  packit_service/worker/handlers/github_handlers.py
  tests_requre/database/conftest.py
  tests_requre/database/test_models.py
Labels: mergeit

#531 Add missing test
  tests_requre/database/test_views.py
Labels: mergeit

#524 Use the configured COPR project when triggering Testing Farm
  packit_service/worker/testing_farm.py
Labels: mergeit

#532 Get testing farm trigger from db
  packit_service/service/events.py
  tests/unit/test_events.py
  tests_requre/database/test_models.py
Labels: mergeit

#537 [files/scripts/whitelist] Remove redundant messages
  files/scripts/whitelist.py
Labels: mergeit

#534 Log Package Versions
  packit_service/log_versions.py
  packit_service/service/app.py
  packit_service/service/views.py
  packit_service/worker/jobs.py
Labels: mergeit

#533 Add a unit test checking the payload to trigger Testing Factory
  CONTRIBUTING.md
  Makefile
  packit_service/worker/testing_farm.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#541 Fix release event and test event parsing with database
  packit_service/models.py
  packit_service/service/db_triggers.py
  packit_service/service/events.py
  tests/unit/test_copr_build.py
  tests/unit/test_steve.py
  tests_requre/database/conftest.py
  tests_requre/database/test_events.py
  tests_requre/database/test_models.py
  tests_requre/database/test_views.py
Labels: mergeit

#542 Small fixes and improvements in models.py
  packit_service/models.py
Labels: mergeit

#526 Add script to move data from redis to psql
  alembic/versions/c6250555a36c_.py
Labels: mergeit

#550 Fix the migration script behaviour when pr ID cannot be parsed from t…
  alembic/versions/c6250555a36c_.py
Labels: mergeit

#551 CONTRIBUTING.md#running locally update
  CONTRIBUTING.md
Labels: mergeit

#554 add pull request info to copr build
  packit_service/service/api/copr_builds.py
Labels: mergeit

#549 Rewrite API calls to get data from postgres, remove getting info from…
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/service/api/installations.py
  packit_service/service/api/tasks.py
  packit_service/service/api/whitelist.py
  packit_service/service/events.py
  packit_service/service/models.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/copr_db.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/tasks.py
  packit_service/worker/whitelist.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_copr_build.py
  tests/unit/test_models.py
  tests/unit/test_whitelist.py
Labels: mergeit

#559 Remove PullRequestGithubCheckDownstreamHandler
  packit_service/worker/handlers/__init__.py
  packit_service/worker/handlers/github_handlers.py
Labels: mergeit

#560 Fix bug in api/copr-builds
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  tests_requre/database/conftest.py
  tests_requre/database/test_models.py
Labels: mergeit

#565 Remove test jobs from zuul gating jobs
  zuul.d/zuul.yaml
Labels: mergeit

#555 store build state per chroot in DB
  packit_service/worker/tasks.py
  tests_requre/database/test_tasks.py
Labels: mergeit

#564 JobMetadataConfig.dist_git_branch has been renamed to dist_git_branches
  packit_service/worker/build/build_helper.py
  packit_service/worker/handlers/github_handlers.py
  tests/unit/test_copr_build.py
Labels: mergeit

#561 Optionally Disable Sentry
  docker-compose.yml
  packit_service/config.py
  packit_service/schema.py
  packit_service/sentry_integration.py
  packit_service/service/app.py
  tests/unit/test_config.py
  tests/unit/test_copr_build.py
Labels: mergeit

#568 Rename variable
  packit_service/worker/handlers/github_handlers.py
Labels: mergeit

#573 Look for users also in redis whitelist
  packit_service/worker/whitelist.py
  tests/unit/test_whitelist.py
Labels: mergeit

#574 Add logging into the migration script, remove getting info via Copr API
  alembic/versions/c6250555a36c_.py
Labels: mergeit

#570 store chroot build details in db
  packit_service/models.py
  packit_service/service/events.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/parser.py
  packit_service/worker/tasks.py
  tests/data/fedmsg/copr_build_end.json
  tests/integration/test_listen_to_fedmsg.py
Labels: mergeit

#567 Tests for the API and other changes
  CONTRIBUTING.md
  files/recipe-tests.yaml
  files/run_tests.sh
  packit_service/service/api/copr_builds.py
  tests_requre/service/__init__.py
  tests_requre/service/conftest.py
  tests_requre/service/test_api.py
  tests_requre/service/test_views.py
  tests_requre/test_data/test_fedpkg/tests_requre.openshift_integration.test_fedpkg.FedPkg.test_fedpkg_clone.yaml
Labels: mergeit

#577 Remove some unused files
  Jenkinsfile
  files/scripts/blacklist.py
  inventory-local
Labels: mergeit

#576 Remove redis from whitelist code
  packit_service/worker/whitelist.py
  tests/unit/test_whitelist.py
Labels: mergeit

#515 CentOS integration initial work
  Makefile
  packit_service/config.py
  packit_service/models.py
  packit_service/service/events.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/__init__.py
  packit_service/worker/handlers/centosmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
  packit_service/worker/reporting.py
  packit_service/worker/tasks.py
  packit_service/worker/whitelist.py
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_jobs.py
  tests_requre/database/conftest.py
Labels: mergeit, ready-for-review

#579 changed hardcoded spec file value to SPECS/<repo-name>.spec
  packit_service/config.py
Labels: CentOS Stream, mergeit, ready-for-review

#569 Report build status in Pagure
  packit_service/worker/build/build_helper.py
  packit_service/worker/reporting.py
  tests/unit/test_copr_build.py
  tests/unit/test_reporting.py
Labels: mergeit

#583 [CONTRIBUTING] Remove outdated sections
  CONTRIBUTING.md
Labels: mergeit

#580 Delete zuul.d/*-secret.yaml
  zuul.d/cert-secret.yaml
  zuul.d/chain-secret.yaml
  zuul.d/copr-secret.yaml
  zuul.d/fedora_keytab-secret.yaml
  zuul.d/fullchain-secret.yaml
  zuul.d/httpd_packit-secret.yaml
  zuul.d/id_rsa-secret.yaml
  zuul.d/id_rsa_pub-secret.yaml
  zuul.d/packit_service-secret.yaml
  zuul.d/private_key-secret.yaml
  zuul.d/privkey-secret.yaml
  zuul.d/ssh_config-secret.yaml
  zuul.d/zuul.yaml
Labels: mergeit

#582 add parsing of centos pull-request comments and updates
  packit_service/service/events.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/centosmsg_handlers.py
  packit_service/worker/handlers/comment_action_handler.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
  packit_service/worker/whitelist.py
  tests/data/centosmsg_listener_events.py
  tests/unit/test_events.py
Labels: mergeit, ready-for-review

#584 set packit config name to '.packit.yaml'
  packit_service/config.py
Labels: mergeit, ready-for-review

#578 Fix getting of start and end time in CoprBuildEnd event
  packit_service/models.py
  packit_service/service/events.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/parser.py
  packit_service/worker/tasks.py
  tests/data/fedmsg/copr_build_end.json
  tests/integration/test_listen_to_fedmsg.py
  tests_requre/database/test_models.py
Labels: mergeit

#585 fixed catching of unwanted KeyError exceptions
  packit_service/worker/parser.py
Labels: mergeit, ready-for-review

#586 CentOS related changes
  alembic/versions/f0abb806c3d4_add_project_url_to_gitproject.py
  packit_service/config.py
  packit_service/models.py
  packit_service/service/db_triggers.py
  packit_service/service/events.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/handlers/__init__.py
  packit_service/worker/handlers/centosmsg_handlers.py
  packit_service/worker/handlers/comment_action_handler.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
  packit_service/worker/reporting.py
  packit_service/worker/testing_farm.py
  packit_service/worker/whitelist.py
  tests/conftest.py
  tests/integration/test_handler.py
  tests/integration/test_issue_comment.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_build_helper.py
  tests/unit/test_events.py
  tests/unit/test_jobs.py
  tests/unit/test_steve.py
  tests/unit/test_testing_farm.py
  tests/unit/test_whitelist.py
  tests_requre/database/conftest.py
  tests_requre/database/test_events.py
  tests_requre/database/test_models.py
  tests_requre/database/test_tasks.py
  tests_requre/service/conftest.py
Labels: mergeit

#588 Improve status messages while building
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/fedmsg_handlers.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_copr_build.py
Labels: mergeit

#589 Do not use forks in github
  packit_service/config.py
  packit_service/service/events.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/comment_action_handler.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
  packit_service/worker/testing_farm.py
  packit_service/worker/whitelist.py
  tests/conftest.py
  tests/integration/test_handler.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_config.py
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_testing_farm.py
  tests/unit/test_whitelist.py
  tests_requre/database/test_events.py
Labels: mergeit

#592 Add a script for removing redis data
  files/scripts/remove_redis_data.py
Labels: mergeit
