Repository packit/packit-service, pull requests merged in 2020-07, with the labels that each got.

#676 let handlers use jobconfig only
  packit_service/service/events.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/build/koji_build.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/comment_action_handler.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/pagure_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/testing_farm.py
  packit_service/worker/whitelist.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
  tests/unit/test_koji_build.py
  tests/unit/test_testing_farm.py
  tests/unit/test_whitelist.py
Labels: mergeit, ready-for-review

#712 Rename 'config' to 'service_config'
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/build/koji_build.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/pagure_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/testing_farm.py
  packit_service/worker/whitelist.py
  tests/integration/test_handler.py
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
  tests/unit/test_koji_build.py
  tests/unit/test_testing_farm.py
  tests/unit/test_whitelist.py
  tests_requre/openshift_integration/base.py
Labels: mergeit

#713 Gitlab events dont require whitelist checks
  packit_service/worker/whitelist.py
Labels: mergeit

#715 new test case: make sure spec is discovered and set
  tests/integration/test_issue_comment.py
  tests/unit/test_config.py
Labels: mergeit

#704 Create Celery tasks to run handlers
  packit_service/service/events.py
  packit_service/utils.py
  packit_service/worker/build/babysit.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/build/koji_build.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/comment_action_handler.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/pagure_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/result.py
  packit_service/worker/tasks.py
  packit_service/worker/testing_farm.py
  tests/integration/test_issue_comment.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/integration/test_release_event.py
  tests/spellbook.py
  tests/unit/test_steve.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#720 Sourcery refactor and empty list fix
  packit_service/config.py
  packit_service/service/api/koji_builds.py
  packit_service/service/events.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
Labels: mergeit, refactor

#721 Fix testing farm related bugs after refactoring
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/tasks.py
  tests/integration/test_listen_to_fedmsg.py
Labels: mergeit

#725 Use value of TaskName.testing_farm
  packit_service/worker/handlers/fedmsg_handlers.py
Labels: mergeit

#727 Allow to specify redis password
  alembic/versions/c6250555a36c_.py
  docker-compose.yml
  packit_service/celerizer.py
Labels: mergeit

#728 Fix missing 'msg' key in task results details
  packit_service/worker/build/copr_build.py
Labels: mergeit

#716 Add projects endpoint to the API
  packit_service/models.py
  packit_service/service/api/__init__.py
  packit_service/service/api/projects.py
  tests_requre/conftest.py
  tests_requre/database/test_models.py
  tests_requre/service/test_api.py
Labels: GSOC, mergeit

#730 CoprBuildJobHelper: make sure metadata.pr_id is set
  tests/unit/test_copr_build.py
Labels: mergeit, 🌞 Friday 🤟

#733 Set job type correctly if job config is None
  packit_service/worker/handlers/abstract.py
Labels: mergeit

#735 Drop TaskResultModel, delete /tasks endpoint
  alembic/versions/adbdc1c21d7e_drop_task_results_table.py
  packit_service/models.py
  packit_service/service/api/__init__.py
  packit_service/service/api/tasks.py
  packit_service/worker/tasks.py
  tests_requre/conftest.py
  tests_requre/database/test_models.py
Labels: mergeit

#737 actually check out PR when building it
  packit_service/service/events.py
  packit_service/worker/jobs.py
  tests/unit/test_events.py
Labels: high-prio, mergeit, ready-for-review

#736 Use the last release tag as the commit_sha in IssueCommentEvents
  packit_service/service/events.py
  tests/unit/test_events.py
Labels: mergeit

#738 files/install-[deps-]worker.yaml - unpin sentry-sdk version
  files/install-deps-worker.yaml
  files/install-deps.yaml
Labels: mergeit

#745 Update CONTRIBUTING.md & files/scripts/webhook.py
  CONTRIBUTING.md
  files/scripts/webhook.py
Labels: mergeit

#742 Enable backend_cleanup Celery task to delete old task results
  files/run_worker.sh
  packit_service/celerizer.py
Labels: mergeit

#746 Add /api/project/.../branches endpoint
  packit_service/models.py
  packit_service/service/api/projects.py
  tests_requre/database/test_models.py
  tests_requre/service/test_api.py
Labels: GSOC, mergeit

#748 Revert JobTriggerModel.get(...)
  packit_service/models.py
Labels: GSOC, mergeit

#751 Use Fedora 31 as a base for the workers
  Dockerfile.worker
Labels: mergeit

#747 Fix build hook
  files/docker/Dockerfile
  files/docker/Dockerfile.worker
  files/docker/hooks/build
Labels: mergeit, ready-for-review

#753 Cleanup after "remove image dependency" change
  Dockerfile
  Dockerfile.tests
  Dockerfile.worker
  Dockerfile.worker.prod
  Makefile
  docker-compose.yml
  files/docker/Dockerfile
Labels: mergeit, ready-for-review

#756 Fix Docker Hub CI test builds and update Makefile
  Makefile
  files/install-deps-worker.yaml
  files/zuul-tests.yaml
Labels: mergeit, ready-for-review

#757 Improve service dependency installation approach
  CONTRIBUTING.md
  Makefile
  docker-compose.yml
  files/docker/Dockerfile
  files/docker/Dockerfile.tests
  files/docker/Dockerfile.worker
  files/install-deps-worker.yaml
  files/install-deps.yaml
  files/packit-service-image.yaml
  files/recipe-worker.yaml
  files/run_tests.sh
  files/run_worker.sh
  files/scripts/README.md
  files/tasks/install-ogr-deps.yaml
  files/tasks/install-packit-deps.yaml
  files/tasks/process-source-branch.yaml
  files/test-in-openshift-get-data.yaml
  files/test-in-openshift.yaml
  files/zuul-tests-requre.yaml
  files/zuul-tests.yaml
Labels: mergeit, ready-for-review

#762 [Makefile/docker-compose.yaml] set SOURCE_BRANCH
  Makefile
  docker-compose.yml
Labels: mergeit

#758 copr builds: set commit status URL to FAQ when lack of perms
  packit_service/constants.py
  packit_service/worker/handlers/github_handlers.py
Labels: mergeit

#754 Misc API Changes
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/service/api/projects.py
  packit_service/service/api/testing_farm.py
  packit_service/service/api/utils.py
  tests_requre/database/test_models.py
  tests_requre/service/test_api.py
Labels: API, GSOC, mergeit, ready-for-review

#761 Retry propose downstream when archive is not in PyPI yet
  packit_service/constants.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/tasks.py
  tests/integration/test_release_event.py
Labels: mergeit
