Repository packit/packit-service, pull requests merged in 2020-08, with the labels that each got.

#764 copr settings updates
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: mergeit, ready-for-review

#766 Use integer response code values
  packit_service/service/api/copr_builds.py
  packit_service/service/api/healthz.py
  packit_service/service/api/installations.py
  packit_service/service/api/koji_builds.py
  packit_service/service/api/projects.py
  packit_service/service/api/testing_farm.py
  packit_service/service/api/utils.py
  packit_service/service/api/webhooks.py
  packit_service/service/api/whitelist.py
  tests_requre/service/test_api.py
Labels: mergeit, ready-for-review

#767 Dockerfiles will fail if build arg is missing
  CONTRIBUTING.md
  files/docker/Dockerfile
  files/docker/Dockerfile.tests
  files/docker/Dockerfile.worker
Labels: mergeit

#772 Use notifications repo explicitly as project in GithubAppInstallationHandler
  packit_service/worker/handlers/github_handlers.py
Labels: mergeit

#768 Link SRPMBuildModel to JobTriggerModel
  alembic/versions/726cb0f70c6d_link_srpmbuildmodel_to_jobtriggermodel.py
  packit_service/models.py
  packit_service/worker/build/build_helper.py
  tests_requre/conftest.py
  tests_requre/database/test_models.py
  tests_requre/database/test_tasks.py
Labels: database, mergeit, ready-for-review

#775 Add /api/srpm-builds endpoint
  packit_service/models.py
  packit_service/service/api/__init__.py
  packit_service/service/api/projects.py
  packit_service/service/api/srpm_builds.py
  tests_requre/database/test_models.py
  tests_requre/service/test_api.py
Labels: GSOC, mergeit, ready-for-review

#777 https://github.com/packit-service -> https://github.com/packit
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  files/docker/README.md
  files/install-deps-worker.yaml
  files/install-deps.yaml
  files/recipe-tests.yaml
  files/scripts/README.md
  packit_service/config.py
  packit_service/models.py
  packit_service/service/api/testing_farm.py
  setup.cfg
  tests/functional/test_webhook.py
  tests/integration/test_release_event.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#779 [CONTRIBUTING.md] Database section update
  CONTRIBUTING.md
Labels: mergeit

#776 No updates of Copr boolean values for custom projects and request builder permission if needed
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: mergeit

#783 Fix copr permission exception text
  packit_service/worker/build/copr_build.py
Labels: mergeit

#786 [install-deps-worker.yaml] add rsync for 'oc rsync'
  files/install-deps-worker.yaml
Labels: mergeit

#787 Use job config from handler as a first choice
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
  tests/unit/test_jobs.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#769 Adding project token model and gitlab authentication
  alembic/versions/521433a1fdb0_add_project_authentication_issue_model.py
  files/install-deps.yaml
  packit_service/config.py
  packit_service/models.py
  packit_service/schema.py
  packit_service/service/api/webhooks.py
  tests/unit/test_config.py
  tests/unit/test_webhooks.py
  tests_requre/conftest.py
  tests_requre/database/test_models.py
Labels: mergeit

#788 Fix crash in /api/srpm-builds if job trigger doesnt exist
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/service/api/healthz.py
  packit_service/service/api/srpm_builds.py
  tests_requre/database/test_models.py
  tests_requre/service/test_api.py
Labels: mergeit

#794 Follow new black formatting
  .pre-commit-config.yaml
  alembic/env.py
  alembic/versions/258490f6e667_initial_schema.py
  alembic/versions/521433a1fdb0_add_project_authentication_issue_model.py
  alembic/versions/7a43773ac926_add_bugzillas.py
  alembic/versions/d90948124e46_add_tables_for_triggers_koji_and_tests.py
  packit_service/models.py
  packit_service/sentry_integration.py
  packit_service/service/api/copr_builds.py
  packit_service/service/api/healthz.py
  packit_service/service/api/projects.py
  packit_service/service/api/srpm_builds.py
  packit_service/service/api/testing_farm.py
  packit_service/service/events.py
  packit_service/service/urls.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/comment_action_handler.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/pagure_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/reporting.py
  packit_service/worker/testing_farm.py
  tests/integration/test_handler.py
  tests/integration/test_issue_comment.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_build_helper.py
  tests/unit/test_config.py
  tests/unit/test_copr_build.py
  tests/unit/test_jobs.py
  tests/unit/test_koji_build.py
  tests/unit/test_steve.py
  tests/unit/test_testing_farm.py
  tests/unit/test_whitelist.py
  tests_requre/conftest.py
  tests_requre/database/test_models.py
Labels: mergeit

#792 Make PullRequestLabelPagureEvent JSON serializable
  packit_service/service/events.py
  packit_service/worker/parser.py
  tests/unit/test_events.py
Labels: mergeit
