Repository packit/packit-service, pull requests merged in 2020-06, with the labels that each got.

#643 Use list for copr targets
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: mergeit

#648 Fix get_config_for_handler_kls
  packit_service/worker/jobs.py
  tests/unit/test_jobs.py
Labels: mergeit

#634 Event & Handler for Pagure PR labels added
  CONTRIBUTING.md
  docker-compose.yml
  packit_service/config.py
  packit_service/schema.py
  packit_service/service/events.py
  packit_service/worker/handlers/__init__.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/comment_action_handler.py
  packit_service/worker/handlers/pagure_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
  tests/conftest.py
  tests/data/centosmsg/pull-request.comment.added.json
  tests/data/centosmsg/pull-request.new.json
  tests/data/centosmsg/pull-request.tag.added.json
  tests/data/centosmsg/pull-request.updated.json
  tests/data/centosmsg_listener_events.py
  tests/data/fedmsg/distgit_commit.json
  tests/data/webhooks/github/installation_added.json
  tests/data/webhooks/github/installation_created.json
  tests/data/webhooks/github/issue_comment_packit_only.json
  tests/data/webhooks/github/issue_comment_wrong_packit_command.json
  tests/data/webhooks/github/issue_propose_update.json
  tests/data/webhooks/github/pr.json
  tests/data/webhooks/github/pr_comment_build.json
  tests/data/webhooks/github/pr_comment_copr_build.json
  tests/data/webhooks/github/pr_comment_embedded_command.json
  tests/data/webhooks/github/pr_comment_empty.json
  tests/data/webhooks/github/push.json
  tests/data/webhooks/github/push_branch.json
  tests/data/webhooks/github/release.json
  tests/data/webhooks/release_event.json
  tests/data/webhooks/testing_farm/results.json
  tests/data/webhooks/testing_farm/results_error.json
  tests/integration/test_handler.py
  tests/integration/test_issue_comment.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_config.py
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_koji_build.py
  tests/unit/test_reporting.py
  tests_requre/openshift_integration/test_copr.py
Labels: mergeit

#656 Don't deploy OpenShift for the tests
  .zuul.yaml
  Makefile
  files/zuul-tests.yaml
Labels: mergeit

#667 Set `__version__` to None by default
  packit_service/__init__.py
Labels: mergeit, 🌞 Friday 🤟

#666 Add global service config
  tests/conftest.py
  tests_requre/conftest.py
Labels: mergeit, 🌞 Friday 🤟

#660 process properly multiple jobs with the same type
  Makefile
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/comment_action_handler.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/pagure_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/testing_farm.py
  tests/integration/test_issue_comment.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/integration/test_release_event.py
  tests/spellbook.py
  tests/unit/test_jobs.py
  tests/unit/test_steve.py
Labels: mergeit

#654 Set job_config for babysit task
  packit_service/worker/build/babysit.py
  packit_service/worker/jobs.py
  packit_service/worker/tasks.py
  tests/conftest.py
  tests/integration/test_babysit.py
  tests/unit/test_jobs.py
  tests_requre/conftest.py
  tests_requre/database/test_tasks.py
Labels: mergeit

#629 Listen to gitlab hook and parsing events
  packit_service/models.py
  packit_service/service/api/webhooks.py
  packit_service/service/events.py
  packit_service/worker/parser.py
  tests/conftest.py
  tests/data/webhooks/gitlab/mr_event.json
  tests/data/webhooks/gitlab/mr_update_event.json
  tests/unit/test_events.py
  tests_requre/conftest.py
  tests_requre/database/test_events.py
Labels: mergeit

#670 Typo fix "tests-requre" -> "test_requre"
  CONTRIBUTING.md
Labels: mergeit

#641 Restructure the log pages
  packit_service/models.py
  packit_service/service/static/packit.png
  packit_service/service/static/style.css
  packit_service/service/templates/build_info.html
  packit_service/service/templates/layout.html
  packit_service/service/templates/srpm_logs.html
  packit_service/service/urls.py
  packit_service/service/views.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/build/koji_build.py
  packit_service/worker/handlers/fedmsg_handlers.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_copr_build.py
  tests/unit/test_koji_build.py
  tests/unit/test_views.py
  tests_requre/conftest.py
  tests_requre/service/test_views.py
Labels: mergeit, 🌞 Friday 🤟

#657 Koji reporing
  packit_service/config.py
  packit_service/constants.py
  packit_service/models.py
  packit_service/service/events.py
  packit_service/trigger_mapping.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/koji_build.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
  packit_service/worker/whitelist.py
  tests/conftest.py
  tests/data/fedmsg/koji_build_scratch_end.json
  tests/data/fedmsg/koji_build_scratch_start.json
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_events.py
  tests/unit/test_jobs.py
  tests_requre/conftest.py
  tests_requre/database/test_events.py
Labels: mergeit

#677 Improve the message when marking issues as stale
  .github/stale.yml
Labels: mergeit

#674 Merge chroots and do pagination (API) in SQL instead of python
  docker-compose.yml
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  tests_requre/conftest.py
  tests_requre/database/test_models.py
  tests_requre/service/test_api.py
Labels: mergeit, ready-for-review

#679 Fix method names in koji reporting
  packit_service/models.py
  packit_service/worker/handlers/fedmsg_handlers.py
  tests/integration/test_listen_to_fedmsg.py
Labels: mergeit

#669 Push with podman
  Makefile
  files/deployment.yaml
  files/install-openshift.yaml
Labels: mergeit

#655 [tests_requre/database/test_events.py] test_pagure_pr_tag_added_event
  CONTRIBUTING.md
  Makefile
  tests_requre/conftest.py
  tests_requre/database/test_events.py
Labels: mergeit

#681 Count GitHub webhook calls
  files/install-deps-worker.yaml
  files/install-deps.yaml
  packit_service/service/api/webhooks.py
  packit_service/service/app.py
  packit_service/service/urls.py
  tests/unit/test_views.py
  tests_requre/service/conftest.py
Labels: mergeit

#678 Add API endpoint for fetching testing farm results
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/service/api/testing_farm.py
  tests_requre/database/test_models.py
  tests_requre/service/test_api.py
Labels: mergeit

#662 PagurePullRequestLabelHandler to create a bug and PR flag
  CONTRIBUTING.md
  alembic/versions/7a43773ac926_add_bugzillas.py
  packit_service/models.py
  packit_service/service/events.py
  packit_service/worker/handlers/pagure_handlers.py
  packit_service/worker/psbugzilla.py
  packit_service/worker/reporting.py
  tests/unit/test_psbugzilla.py
  tests_requre/conftest.py
  tests_requre/database/test_models.py
Labels: mergeit

#687 Match handler for propose update comment
  packit_service/trigger_mapping.py
  tests/integration/test_issue_comment.py
  tests/unit/test_jobs.py
Labels: mergeit

#691 [files/deployment.yaml] Don't set container_engine
  files/deployment.yaml
Labels: mergeit

#690 Add CORS Headers to the API
  packit_service/service/api/copr_builds.py
  packit_service/service/api/koji_builds.py
  packit_service/service/api/testing_farm.py
Labels: mergeit

#668 Fix example for 'whitelist.py waiting'
  files/scripts/README.md
Labels: 🌞 Friday 🤟

#693 Regenerate tests_requre/openshift_integration/test_data/
  CONTRIBUTING.md
  Makefile
  tests_requre/openshift_integration/test_data/test_fedpkg/tests_requre.openshift_integration.test_fedpkg.FedPkg.test_fedpkg_clone.yaml
Labels: mergeit

#694 [packit-service] Copr enhancements
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: mergeit, 🌞 Friday 🤟

#696 tests_requre regenerate
  .pre-commit-config.yaml
  .zuul.yaml
  files/zuul-pre-commit.yaml
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/build/koji_build.py
  packit_service/worker/handlers/pagure_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/whitelist.py
  tests/functional/test_webhook.py
  tests/unit/test_views.py
  tests/unit/test_whitelist.py
  tests_requre/openshift_integration/test_data/test_fedpkg/tests_requre.openshift_integration.test_fedpkg.FedPkg.test_fedpkg_clone.yaml
Labels: mergeit

#675 Change the handler classes code to have more separate attributes
  packit_service/models.py
  packit_service/service/events.py
  packit_service/worker/build/babysit.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/build/koji_build.py
  packit_service/worker/handlers/__init__.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/comment_action_handler.py
  packit_service/worker/handlers/fedmsg_handlers.py
  packit_service/worker/handlers/github_handlers.py
  packit_service/worker/handlers/pagure_handlers.py
  packit_service/worker/handlers/testing_farm_handlers.py
  packit_service/worker/jobs.py
  packit_service/worker/testing_farm.py
  packit_service/worker/whitelist.py
  tests/integration/test_babysit.py
  tests/integration/test_handler.py
  tests/integration/test_issue_comment.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_koji_build.py
  tests/unit/test_steve.py
  tests/unit/test_testing_farm.py
  tests/unit/test_whitelist.py
Labels: mergeit

#698 Fix mistaken attributes in PagurePullRequestLabelHandler after refactor
  packit_service/worker/handlers/pagure_handlers.py
Labels: mergeit

#700 Don't use 'package_config' when there is none
  packit_service/worker/jobs.py
Labels: mergeit

#699 [files/deployment.yaml] switch without_* to with_*
  .zuul.yaml
  files/deployment.yaml
Labels: mergeit, 🌞 Friday 🤟

#705 [PagurePullRequestLabelHandler] product version has changed
  packit_service/worker/handlers/pagure_handlers.py
  tests/integration/test_handler.py
Labels: mergeit

#707 Use thread-local sqlalchemy session
  packit_service/models.py
Labels: mergeit
