Repository packit/packit-service, pull requests merged in 2022-10, with the labels that each got.

#1680 Improve link in reporting about custom Coprs
  packit_service/constants.py
  packit_service/worker/helpers/build/copr_build.py
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
Labels: mergeit

#1684 Normalise default Copr project name
  packit_service/worker/helpers/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: mergeit

#1683 fix: finish off the refactor of the events' actor
  packit_service/worker/events/gitlab.py
  packit_service/worker/parser.py
  tests/unit/test_events.py
Labels: mergeit

#1689 testing farm composes: pick distro if user requested it
  packit_service/worker/helpers/testing_farm.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#1688 Improve table on github check page
  packit_service/worker/reporting.py
  tests/unit/test_reporting.py
Labels: mergeit, has-release-notes

#1656 Deprecate production_build in favour of upstream_koji_build
  packit_service/constants.py
  packit_service/trigger_mapping.py
  packit_service/worker/events/github.py
  packit_service/worker/handlers/koji.py
  packit_service/worker/helpers/build/koji_build.py
  packit_service/worker/jobs.py
  tests/integration/test_check_rerun.py
  tests/integration/test_handler.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/unit/test_copr_build.py
  tests/unit/test_koji_build.py
Labels: mergeit

#1704 use latest bodhi v6 client
  files/install-deps-worker.yaml
  files/install-deps.yaml
Labels: mergeit

#1706 fix(gitlab): reword the initial issue with token
  packit_service/constants.py
  packit_service/service/api/webhooks.py
Labels: ready-for-review, mergeit

#1719 Fix mix
  docker-compose.yml
  files/install-deps-worker.yaml
  packit_service/models.py
  packit_service/worker/tasks.py
Labels: mergeit

#1716 Do not repeat custom copr restriction message
  packit_service/worker/handlers/copr.py
  packit_service/worker/handlers/testing_farm.py
  packit_service/worker/helpers/build/copr_build.py
  packit_service/worker/helpers/job_helper.py
  packit_service/worker/reporting.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_reporting.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#1678 Move job handler's pre-checks in a new class
  packit_service/worker/checker/__init__.py
  packit_service/worker/checker/abstract.py
  packit_service/worker/checker/bodhi.py
  packit_service/worker/checker/copr.py
  packit_service/worker/checker/distgit.py
  packit_service/worker/checker/forges.py
  packit_service/worker/checker/koji.py
  packit_service/worker/checker/testing_farm.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/bodhi.py
  packit_service/worker/handlers/copr.py
  packit_service/worker/handlers/distgit.py
  packit_service/worker/handlers/forges.py
  packit_service/worker/handlers/koji.py
  packit_service/worker/handlers/mixin.py
  packit_service/worker/handlers/testing_farm.py
  packit_service/worker/helpers/build/babysit.py
  packit_service/worker/jobs.py
  packit_service/worker/mixin.py
  tests/integration/test_dg_commit.py
  tests/integration/test_handler.py
  tests/integration/test_pr_comment.py
  tests/unit/test_distgit.py
  tests/unit/test_jobs.py
Labels: mergeit

#1726 Remove _test_check_names attribute from BaseBuildJobHelper
  packit_service/worker/helpers/build/build_helper.py
  packit_service/worker/helpers/testing_farm.py
Labels: mergeit
