Repository packit/packit-service, pull requests merged in 2022-02, with the labels that each got.

#1332 Bodhi update for koji build
  packit_service/constants.py
  packit_service/worker/allowlist.py
  packit_service/worker/events/__init__.py
  packit_service/worker/events/koji.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/bodhi.py
  packit_service/worker/handlers/distgit.py
  packit_service/worker/handlers/koji.py
  packit_service/worker/parser.py
  packit_service/worker/tasks.py
  tests/data/fedmsg/koji_build_completed_epel8.json
  tests/data/fedmsg/koji_build_completed_f35.json
  tests/data/fedmsg/koji_build_completed_old_format.json
  tests/data/fedmsg/koji_build_completed_rawhide.json
  tests/data/fedmsg/koji_build_start_epel8.json
  tests/data/fedmsg/koji_build_start_f35.json
  tests/data/fedmsg/koji_build_start_old_format.json
  tests/data/fedmsg/koji_build_start_rawhide.json
  tests/integration/test_bodhi_update.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_events.py
  tests/unit/test_jobs.py
  tests/unit/test_koji_build.py
  tests_requre/database/test_events.py
Labels: mergeit

#1336 Update Koji build states
  packit_service/worker/events/koji.py
  packit_service/worker/handlers/__init__.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/koji.py
  packit_service/worker/tasks.py
  tests/conftest.py
  tests/integration/test_bodhi_update.py
  tests/integration/test_koji_build.py
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_jobs.py
Labels: mergeit

#1303 Introduce `/packit rebuild-failed` and `/packit retest-failed`
  packit_service/models.py
  packit_service/worker/events/__init__.py
  packit_service/worker/events/comment.py
  packit_service/worker/events/event.py
  packit_service/worker/events/github.py
  packit_service/worker/events/gitlab.py
  packit_service/worker/events/pagure.py
  packit_service/worker/handlers/copr.py
  packit_service/worker/handlers/distgit.py
  packit_service/worker/handlers/koji.py
  packit_service/worker/handlers/testing_farm.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
  packit_service/worker/testing_farm.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests_requre/conftest.py
  tests_requre/database/test_events.py
  tests_requre/database/test_models.py
Labels: mergeit

#1339 Reduce db connections for events
  packit_service/worker/events/copr.py
  packit_service/worker/events/event.py
  packit_service/worker/events/github.py
  packit_service/worker/events/gitlab.py
  packit_service/worker/events/koji.py
  packit_service/worker/events/testing_farm.py
  packit_service/worker/jobs.py
  tests/integration/test_bodhi_update.py
  tests/integration/test_koji_build.py
Labels: refactor, mergeit, 🌞 friday 🤟

#1341 babysit TF: some events don't have a matching DB runs
  packit_service/worker/events/event.py
Labels: mergeit, 🌞 friday 🤟

#1347 test deployment: don't check repos being up to date
  files/deployment.yaml
Labels: mergeit

#1346 Align with packit#1357 code
  tests/unit/test_config.py
Labels: mergeit

#1335 Improvements to DB model names
  alembic/versions/73a28911901f_improve_db_model_naming.py
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/service/api/installations.py
  packit_service/service/api/koji_builds.py
  packit_service/service/api/runs.py
  packit_service/service/api/testing_farm.py
  packit_service/service/api/utils.py
  packit_service/worker/build/babysit.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/build/koji_build.py
  packit_service/worker/events/copr.py
  packit_service/worker/events/event.py
  packit_service/worker/events/koji.py
  packit_service/worker/events/testing_farm.py
  packit_service/worker/handlers/copr.py
  packit_service/worker/handlers/forges.py
  packit_service/worker/handlers/koji.py
  packit_service/worker/handlers/testing_farm.py
  packit_service/worker/parser.py
  packit_service/worker/testing_farm.py
  tests/integration/test_babysit.py
  tests/integration/test_bodhi_update.py
  tests/integration/test_installation.py
  tests/integration/test_koji_build.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_koji_build.py
  tests/unit/test_testing_farm.py
  tests/unit/test_views.py
  tests_requre/conftest.py
  tests_requre/database/test_events.py
  tests_requre/database/test_models.py
  tests_requre/database/test_tasks.py
  tests_requre/service/test_api.py
Labels: mergeit

#1345 Rename tests_requre test suite and zuul job
  .pre-commit-config.yaml
  .zuul.yaml
  CONTRIBUTING.md
  Makefile
  files/check-inside-openshift.yaml
  files/run_tests.sh
  tests_openshift/README.md
  tests_openshift/__init__.py
  tests_openshift/conftest.py
  tests_openshift/database/__init__.py
  tests_openshift/database/test_allowlist.py
  tests_openshift/database/test_events.py
  tests_openshift/database/test_models.py
  tests_openshift/database/test_tasks.py
  tests_openshift/openshift_integration/__init__.py
  tests_openshift/openshift_integration/base.py
  tests_openshift/openshift_integration/test_copr.py
  tests_openshift/openshift_integration/test_data/README.md
  tests_openshift/openshift_integration/test_data/test_fedpkg/tests_openshift.openshift_integration.test_fedpkg.FedPkg.test_fedpkg_clone.yaml
  tests_openshift/openshift_integration/test_data/test_fedpkg/tests_openshift.openshift_integration.test_fedpkg.FedPkg.test_fedpkg_clone.yaml.static_tmp_1_1.tar.xz
  tests_openshift/openshift_integration/test_pkgtool.py
  tests_openshift/openshift_integration/test_sandcastle.py
  tests_openshift/service/__init__.py
  tests_openshift/service/conftest.py
  tests_openshift/service/test_api.py
Labels: mergeit

#1349 Implement 1-n mapping between build and test targets
  packit_service/constants.py
  packit_service/worker/allowlist.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/build/koji_build.py
  packit_service/worker/events/comment.py
  packit_service/worker/events/event.py
  packit_service/worker/events/github.py
  packit_service/worker/handlers/copr.py
  packit_service/worker/handlers/koji.py
  packit_service/worker/handlers/testing_farm.py
  packit_service/worker/jobs.py
  packit_service/worker/tasks.py
  packit_service/worker/testing_farm.py
  tests/integration/test_check_rerun.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_koji_build.py
  tests/unit/test_testing_farm.py
  tests_openshift/database/test_events.py
Labels: mergeit

#1352 Use srpm deps from package config in Copr request
  packit_service/worker/build/copr_build.py
  packit_service/worker/handlers/copr.py
  tests/unit/test_copr_build.py
Labels: mergeit

#1357 Parse koji events correctly
  packit_service/worker/parser.py
  tests/conftest.py
  tests/spellbook.py
  tests/unit/test_events.py
Labels: mergeit

#1358 Use index of job config in the Copr source script
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: mergeit

#1360 compose: Tweak the UID used for services
  docker-compose.yml
Labels: mergeit

#1359 Improve examples of using packit-service locally
  CONTRIBUTING.md
Labels: mergeit
