Repository packit/packit-service, pull requests merged in 2022-03, with the labels that each got.

#1363 Switch to mod_wsig-express
  docker-compose.yml
  files/install-deps.yaml
  files/packit-httpd.conf
  files/run_httpd.sh
  files/tasks/httpd.yaml
  packit_service/config.py
Labels: mergeit

#1366 Set default loglevel for workers to debug
  files/run_worker.sh
Labels: mergeit

#1371 compose: Allow the server name to be fully configurable
  files/run_httpd.sh
Labels: mergeit

#1370 Use the latest stable Fedora chroot to build SRPMs in Copr
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: mergeit

#1365 Few docker-compose.yml updates
  docker-compose.yml
Labels: mergeit

#1372 Use 'eyes' instead of 'thumbsup/+1' as a reaction to /packit comment
  .github/PULL_REQUEST_TEMPLATE.md
  packit_service/constants.py
  packit_service/worker/jobs.py
  tests/integration/test_issue_comment.py
  tests/integration/test_pr_comment.py
  tests/unit/test_jobs.py
Labels: mergeit

#1337 Save progress of propose-downstream and make it available via API
  alembic/versions/6c9e1df74fa0_save_propose_downstream.py
  packit_service/models.py
  packit_service/service/api/__init__.py
  packit_service/service/api/propose_downstream.py
  packit_service/service/api/utils.py
  packit_service/service/urls.py
  packit_service/utils.py
  packit_service/worker/handlers/distgit.py
  tests/integration/test_issue_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_steve.py
  tests_openshift/conftest.py
  tests_openshift/database/test_models.py
  tests_openshift/service/test_api.py
Labels: mergeit

#1378 Use nvr for bodhi updates
  packit_service/worker/events/koji.py
  packit_service/worker/handlers/bodhi.py
  packit_service/worker/parser.py
  tests/integration/test_bodhi_update.py
  tests/unit/test_events.py
Labels: mergeit

#1381 Restart the httpd server every 8 hours
  files/run_httpd.sh
Labels: mergeit

#1383 Build to test target - use always the test job config
  packit_service/worker/build/copr_build.py
  tests/integration/test_pr_comment.py
  tests/unit/test_build_helper.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#1384 feat(copr): allow disabling of network access during build
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: copr, mergeit, 🌞 friday 🤟

#1367 fix(tests): update mocks to refactored release class
  tests/integration/test_issue_comment.py
Labels: refactor, testing, mergeit

#1382 Send PR-specific env.vars. to TF
  packit_service/worker/testing_farm.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/unit/test_testing_farm.py
Labels: mergeit, 🌞 friday 🤟

#1386 Create a target to perform alembic revision
  CONTRIBUTING.md
  Makefile
Labels: mergeit

#1389 Fix task names for Koji
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/koji.py
  packit_service/worker/tasks.py
Labels: mergeit

#1392 Copr result event needs to match the job config
  packit_service/worker/handlers/copr.py
  tests/conftest.py
  tests/data/fedmsg/srpm_build_end.json
  tests/data/fedmsg/srpm_build_start.json
  tests/integration/test_listen_to_fedmsg.py
  tests/unit/test_events.py
Labels: mergeit

#1396 The check for owner/project matching needs to be done for all results
  packit_service/worker/handlers/copr.py
  tests/integration/test_listen_to_fedmsg.py
Labels: mergeit

#1395 fix(copr): comment when Copr project is not found
  packit_service/worker/build/copr_build.py
Labels: user-experience, copr, mergeit, 🌞 friday 🤟, has-release-notes

#1394 Add check for internal TF tests job for builds as well
  packit_service/constants.py
  packit_service/worker/handlers/copr.py
  packit_service/worker/handlers/testing_farm.py
  tests/integration/test_pr_comment.py
Labels: mergeit

#1397 Report better message when we fail updating our chroot set
  packit_service/constants.py
  packit_service/worker/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: mergeit, 🌞 friday 🤟

#1399 Message internal TF not allowed for builds and tests - make it more clear
  packit_service/constants.py
  tests/integration/test_pr_comment.py
Labels: mergeit

#1400 webhook call metrics: label with PID
  packit_service/service/api/webhooks.py
Labels: mergeit

#1398 Add target to test database with docker compose
  CONTRIBUTING.md
  Makefile
Labels: mergeit

#1401 Add relationship between srcgit pr and distgit pr
  CONTRIBUTING.md
  alembic/versions/855bc0b691c2_add_source_git_pr_and_dist_git_pr.py
  packit_service/models.py
  tests_openshift/conftest.py
  tests_openshift/database/test_models.py
Labels: mergeit

#1390 Parse pagure.pull-request.flag.* into PullRequestFlagPagureEvent
  docker-compose.yml
  packit_service/worker/events/enums.py
  packit_service/worker/events/event.py
  packit_service/worker/events/gitlab.py
  packit_service/worker/events/pagure.py
  packit_service/worker/jobs.py
  packit_service/worker/parser.py
  tests/data/fedmsg/pagure_pr_flag_updated.json
  tests/unit/test_events.py
Labels: mergeit

#1410 update username and contact email to "Packit <hello@packit.dev>"
  files/check-inside-openshift.yaml
  files/gitconfig
  setup.cfg
Labels: mergeit

#1402 Fix propose downstream bugs
  packit_service/worker/handlers/distgit.py
  packit_service/worker/tasks.py
  tests/integration/test_issue_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_steve.py
Labels: mergeit

#1416 Don't add commit comments for non final states
  .pre-commit-config.yaml
  packit_service/worker/reporting.py
Labels: mergeit

#1419 fix(tests): Update mock object with _files_to_sync_used
  tests/unit/test_testing_farm.py
Labels: mergeit

#1417 Support for packit instance configuration
  packit_service/config.py
  packit_service/schema.py
  packit_service/worker/build/build_helper.py
  packit_service/worker/build/copr_build.py
  packit_service/worker/jobs.py
  tests/conftest.py
  tests/data/fedmsg/copr_build_end.json
  tests/data/fedmsg/copr_build_start.json
  tests/data/fedmsg/srpm_build_end.json
  tests/data/fedmsg/srpm_build_start.json
  tests/data/webhooks/github/checkrun_rerequested.json
  tests/integration/test_bodhi_update.py
  tests/integration/test_check_rerun.py
  tests/integration/test_dg_commit.py
  tests/integration/test_issue_comment.py
  tests/integration/test_koji_build.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_allowlist.py
  tests/unit/test_events.py
  tests/unit/test_steve.py
Labels: mergeit

#1424 Update black version in pre-commit to fix the CI failures
  .pre-commit-config.yaml
Labels: mergeit

#1421 Issue repository can be used for failures of downstream jobs
  packit_service/config.py
  packit_service/worker/handlers/bodhi.py
  packit_service/worker/handlers/distgit.py
  tests/integration/test_bodhi_update.py
  tests/integration/test_dg_commit.py
  tests/unit/test_config.py
Labels: mergeit

#1408 Add scratch attribute to koji builds
  alembic/versions/46b37040cb19_add_koji_build_scratch_attribute.py
  packit_service/models.py
  packit_service/worker/build/koji_build.py
  packit_service/worker/events/koji.py
  tests_openshift/conftest.py
  tests_openshift/database/test_models.py
Labels: mergeit
