Repository packit/packit-service, pull requests merged in 2022-09, with the labels that each got.

#1636 SRPMs are built in Copr by default for installations since September 6
  packit_service/constants.py
  packit_service/models.py
  packit_service/worker/handlers/copr.py
  packit_service/worker/helpers/build/copr_build.py
  tests/integration/test_check_rerun.py
  tests/integration/test_pr_comment.py
  tests/unit/test_copr_build.py
Labels: mergeit

#1643 GithubInstallationModel.repositories is list of project ids
  packit_service/models.py
  tests/integration/test_check_rerun.py
  tests/integration/test_pr_comment.py
  tests/unit/test_copr_build.py
Labels: mergeit

#1637 Add oldrev field to MergeRequestGitlabEvent
  packit_service/worker/events/gitlab.py
  packit_service/worker/parser.py
  tests/unit/test_events.py
Labels: mergeit

#1649 Fix the check of installation date for SRPM builds
  packit_service/models.py
  packit_service/worker/handlers/copr.py
  tests/unit/test_copr_build.py
Labels: mergeit

#1644 Solo execution pool & --autoscale -> --concurrency
  files/run_worker.sh
Labels: mergeit

#1652 Refactor functionality for timezone-awareness checking
  packit_service/utils.py
  packit_service/worker/handlers/copr.py
  packit_service/worker/monitoring.py
Labels: mergeit

#1663 Don't log Testing Farm token
  packit_service/worker/handlers/abstract.py
  packit_service/worker/helpers/testing_farm.py
Labels: mergeit

#1638 Use packit_forge_project_allowed key from copr
  packit_service/constants.py
  packit_service/worker/helpers/build/copr_build.py
  tests/integration/test_handler.py
  tests/unit/test_build_helper.py
  tests/unit/test_copr_build.py
Labels: mergeit

#1667 Fix wording for restricting copr builds
  packit_service/constants.py
Labels: mergeit

#1669 Improve testing farm reporting
  alembic/versions/a619bd414ff0_add_build_status_enum.py
  packit_service/constants.py
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/service/api/runs.py
  packit_service/worker/events/comment.py
  packit_service/worker/handlers/copr.py
  packit_service/worker/handlers/testing_farm.py
  packit_service/worker/helpers/build/babysit.py
  packit_service/worker/helpers/build/build_helper.py
  packit_service/worker/helpers/build/copr_build.py
  packit_service/worker/helpers/build/koji_build.py
  tests/conftest.py
  tests/integration/test_babysit.py
  tests/integration/test_check_rerun.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/unit/test_copr_build.py
  tests/unit/test_koji_build.py
  tests/unit/test_testing_farm.py
  tests_openshift/conftest.py
  tests_openshift/database/test_events.py
  tests_openshift/database/test_models.py
  tests_openshift/database/test_tasks.py
Labels: mergeit

#1670 Fix query for custom copr project
  packit_service/worker/helpers/build/copr_build.py
  tests/unit/test_copr_build.py
Labels: mergeit

#1671 Move the check for event and job identifiers equality
  packit_service/worker/jobs.py
  tests/unit/test_jobs.py
Labels: mergeit

#1672 Fix instructions for using live data
  CONTRIBUTING.md
Labels: mergeit

#1673 Deduce copr targets
  packit_service/worker/helpers/build/build_helper.py
  packit_service/worker/helpers/build/copr_build.py
  tests/unit/test_build_helper.py
Labels: ready-for-review, mergeit

#1676 Avoid double /docs in the URL
  packit_service/constants.py
Labels: mergeit

#1658 Implement triggering TF with build from other PR
  packit_service/models.py
  packit_service/service/api/testing_farm.py
  packit_service/utils.py
  packit_service/worker/celery_task.py
  packit_service/worker/events/event.py
  packit_service/worker/handlers/abstract.py
  packit_service/worker/handlers/forges.py
  packit_service/worker/handlers/testing_farm.py
  packit_service/worker/helpers/build/copr_build.py
  packit_service/worker/helpers/testing_farm.py
  packit_service/worker/jobs.py
  tests/integration/test_bodhi_update.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/unit/test_copr_build.py
  tests/unit/test_events.py
  tests/unit/test_models.py
  tests/unit/test_testing_farm.py
  tests_openshift/conftest.py
  tests_openshift/database/test_events.py
  tests_openshift/database/test_models.py
Labels: mergeit

#1675 Tf composes
  packit_service/worker/helpers/testing_farm.py
  tests/integration/test_pr_comment.py
  tests/unit/test_testing_farm.py
Labels: ready-for-review, user-experience, testing-farm, mergeit
