Repository packit/packit-service, pull requests merged in 2023-02, with the labels that each got.

#1876 Create TF task as a last step of CoprBuildEndHandler
  packit_service/worker/handlers/copr.py
Labels: mergeit

#1787 Create group models
  CONTRIBUTING.md
  alembic/versions/46b37040cb19_add_koji_build_scratch_attribute.py
  alembic/versions/68ce6a306b30_add_koji_build_groups.py
  alembic/versions/70c369f7ba80_add_explicit_mapping_of_tf_to_copr.py
  alembic/versions/9fe0e970880f_add_copr_build_groups.py
  alembic/versions/a9c49475e9c7_add_testing_farm_groups.py
  docker-compose.yml
  packit_service/models.py
  packit_service/service/api/copr_builds.py
  packit_service/service/api/koji_builds.py
  packit_service/service/api/runs.py
  packit_service/service/api/testing_farm.py
  packit_service/service/api/usage.py
  packit_service/service/api/utils.py
  packit_service/worker/celery_task.py
  packit_service/worker/events/koji.py
  packit_service/worker/handlers/copr.py
  packit_service/worker/handlers/testing_farm.py
  packit_service/worker/helpers/build/copr_build.py
  packit_service/worker/helpers/build/koji_build.py
  packit_service/worker/helpers/testing_farm.py
  packit_service/worker/tasks.py
  tests/conftest.py
  tests/integration/test_check_rerun.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/unit/test_copr_build.py
  tests/unit/test_koji_build.py
  tests/unit/test_testing_farm.py
  tests_openshift/conftest.py
  tests_openshift/database/test_models.py
  tests_openshift/database/test_tasks.py
  tests_openshift/service/test_api.py
Labels: refactor, mergeit, database

#1874 Set hard time limit for tasks
  packit_service/celery_config.py
Labels: mergeit

#1871 Add ER Diagram to CONTRIBUTING.md
  CONTRIBUTING.md
  files/ERDiagram.png
Labels: mergeit

#1884 fix: propagate git-forge exceptions to Sentry
  packit_service/worker/handlers/distgit.py
  packit_service/worker/helpers/sync_release/pull_from_upstream.py
  packit_service/worker/helpers/sync_release/sync_release.py
  tests/integration/test_release_event.py
Labels: mergeit

#1888 Ignore only the top level 'build' directory
  .gitignore
Labels: mergeit

#1887 Fix group-related bugs
  packit_service/service/api/runs.py
  packit_service/worker/handlers/testing_farm.py
  packit_service/worker/helpers/testing_farm.py
  packit_service/worker/tasks.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#1899 Some random readability improvements
  packit_service/worker/jobs.py
Labels: mergeit

#1904 Don't sync default files in pull-from-upstream
  packit_service/worker/handlers/distgit.py
  tests/integration/test_new_hotness_update.py
  tests/integration/test_release_event.py
  tests/unit/test_steve.py
Labels: mergeit

#1913 Allow to set echo arg of sqlalchemy.create_engine() via env. var.
  packit_service/models.py
Labels: mergeit

#1909 feat(config): support regexes for commit triggers
  packit_service/worker/checker/copr.py
  packit_service/worker/checker/koji.py
  tests/unit/test_checkers.py
Labels: mergeit

#1919 Footer ruler in a new line
  packit_service/worker/helpers/build/babysit.py
Labels: mergeit

#1902 Fix/packit service/1879
  CONTRIBUTING.md
  docker-compose.yml
  packit_service/worker/handlers/distgit.py
  packit_service/worker/helpers/sync_release/sync_release.py
  tests/unit/test_distgit.py
Labels: mergeit

#1920 Include trigger identifier for build and test commit statuses
  packit_service/worker/handlers/testing_farm.py
  packit_service/worker/helpers/build/build_helper.py
  packit_service/worker/helpers/job_helper.py
  packit_service/worker/helpers/sync_release/propose_downstream.py
  packit_service/worker/helpers/testing_farm.py
  packit_service/worker/parser.py
  tests/conftest.py
  tests/data/fedmsg/copr_build_end_push.json
  tests/data/fedmsg/copr_build_end_release.json
  tests/integration/test_check_rerun.py
  tests/integration/test_issue_comment.py
  tests/integration/test_listen_to_fedmsg.py
  tests/integration/test_pr_comment.py
  tests/integration/test_release_event.py
  tests/unit/test_allowlist.py
  tests/unit/test_events.py
  tests/unit/test_handler_vm_image.py
  tests/unit/test_steve.py
  tests/unit/test_testing_farm.py
Labels: mergeit

#1932 Trigger identifier improvements
  packit_service/worker/helpers/build/build_helper.py
  tests/conftest.py
  tests/integration/test_listen_to_fedmsg.py
Labels: mergeit

#1928 Workers default to prefork pool
  files/run_worker.sh
Labels: mergeit

#1930 Bump python_requires to 3.9
  setup.cfg
Labels: mergeit

#1933 Remove old SRPM related unused code and unused constants
  packit_service/constants.py
  packit_service/worker/helpers/build/copr_build.py
Labels: mergeit

#1935 fix(tasks): HandlerTaskWithRetry.acks_late = True
  packit_service/worker/tasks.py
Labels: ready-for-review, mergeit
